version: 2.1

executors:

  circleci_latest:
    docker:
      - image: circleci/python:latest


jobs:
  
  build:

    parameters:
      image:
        type: executor

      CC:
        type: string
        default: gcc

      CXX:
        type: string
        default: g++

      buildtype:
        type: string
        default: debug
      
      buildargs: srting
        default: ""

     executor: << parameters.image >>  
    working_directory: ~/korali
    steps:
      - checkout
      - run:
          name: Build and test
          command: |
            CC=<< parameters.CC >> CXX=<< parameters.CXX >> meson setup build --prefix=~/test_install --buildtype=<< parameters.buildtype >>
            meson -C build compile
            meson -C build install
            source tools/helper/set_env.sh build
            meson -C build test
       
      - store_artifacts:
          path: build/meson-logs

workflows:
  
  circleci_latest_gcc:
    
    jobs:
      -build:
        name: release
        buildtypr: release
