version: 2.1

executors:
  circleci_latest:
    docker:
      - image: docker.io/cselab/ubuntu_openmpi:rolling

jobs:
  build:
    parameters:
      image:
        type: executor
      CC:
        type: string
        default: gcc
      CXX:
        type: string
        default: g++
      buildtype:
        type: string
        default: debug
      buildargs: 
        type: string
        default: ""
    executor: << parameters.image >>  
    working_directory: ~/korali
    steps:
      - checkout
      - run:
          name: Build and test and install
          command: |
            CC=<< parameters.CC >> CXX=<< parameters.CXX >> meson setup build --prefix=~/test_install --buildtype=<< parameters.buildtype >>
            meson -C build compile
            source tools/helper/set_env.sh build
            meson -C build test
            meson -C build install
      - store_artifacts:
          path: build/meson-logs

workflows:
  circleci_latest_gcc:
    jobs:
      - build:
          name: release
          image: circleci_latest
          buildtype: release
